LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;

PACKAGE COMPONENTES IS
COMPONENT FF_D IS
	PORT(d,clk,enable,clear:IN STD_LOGIC;
		 q,q_not:BUFFER STD_LOGIC);
END COMPONENT;

COMPONENT FF_JK IS
	PORT(j,k,clk,enable,clear,preset:IN STD_LOGIC;
		q,q_not:BUFFER STD_LOGIC);
END COMPONENT;

COMPONENT REGISTRADOR_8BITS_ARMAZENAMENTO IS
	PORT(a:IN  STD_LOGIC_VECTOR(7 DOWNTO 0);	
		 clk,enable,clear: IN STD_LOGIC;
		 b:OUT  STD_LOGIC_VECTOR(7 DOWNTO 0));
END COMPONENT;



COMPONENT disp1 IS
PORT (display1 : IN STD_LOGIC_VECTOR (3 DOWNTO 0);
	  a1,b1,c1,d1,e1,f1,g1: out STD_LOGIC);
END COMPONENT;

COMPONENT VERIFICADOR_SENHA IS
	PORT(b0,b1,b2,b3,clk:IN STD_LOGIC;
		 senha_reg:IN STD_LOGIC_VECTOR(7 DOWNTO 0);
		 dig1,dig2:OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
		 circuito_ativo: OUT STD_LOGIC;
		 confirmacao:BUFFER STD_LOGIC);
END COMPONENT;


COMPONENT FILTRO_BOTAO IS
	GENERIC(frequencia:INTEGER :=333333);
	PORT (botao,clk: IN  STD_LOGIC;
          botao_filtrado:OUT STD_LOGIC);
END COMPONENT;


COMPONENT GERADOR_DE_PULSO IS
	GENERIC(contador:INTEGER:=100);
	PORT(clk66,enable:IN STD_LOGIC;
		 pulso:OUT STD_LOGIC);
END COMPONENT;

COMPONENT BEEP IS
	GENERIC(tempo:INTEGER:=13333333);
	PORT(pulso,clk:IN STD_LOGIC;
		beep:BUFFER STD_LOGIC);
END COMPONENT;


COMPONENT TROCA_ESTADO IS
	PORT(verificador,monitorador,clk:IN STD_LOGIC;
		 estado:BUFFER STD_LOGIC);
END COMPONENT;

COMPONENT TROCA_SENHA IS
	PORT(saida_verif,clk,b1,b2,b3:IN STD_LOGIC;
		circuito_ativo: OUT STD_LOGIC;
		senha1,senha2: BUFFER STD_LOGIC_VECTOR(3 DOWNTO 0);
		senha_reg: OUT STD_LOGIC_VECTOR(7 DOWNTO 0);
		senha_trocada: BUFFER STD_LOGIC);
END COMPONENT;

COMPONENT CONTADOR_ANEL_3BITS IS
	PORT(clk,enable:IN STD_LOGIC;
	saida0,saida1,saida2:OUT STD_LOGIC);
END COMPONENT;


COMPONENT SELETOR IS
	PORT(clk,verif,troca,monitorador:IN STD_LOGIC;
		 d1_verif,d2_verif,d1_troca,d2_troca,d1_monitorador,d2_monitorador: IN STD_LOGIC_VECTOR(3 DOWNTO 0);
		disp1,disp2:OUT STD_LOGIC_VECTOR(3 DOWNTO 0));
END COMPONENT;

COMPONENT DECODIFICADOR_BCD_7SEG IS
PORT (dig : IN STD_LOGIC_VECTOR (3 DOWNTO 0);
	  a,b,c,d,e,f,g: OUT STD_LOGIC);
END COMPONENT;


COMPONENT CONTADOR_30SEG IS
	PORT(clk,enable:IN STD_LOGIC;
		 d1:BUFFER STD_LOGIC_VECTOR(3 DOWNTO 0);
		 d2:BUFFER STD_LOGIC_VECTOR(3 DOWNTO 0);
		 cheguei_ao_zero:OUT STD_LOGIC);
END COMPONENT;


COMPONENT MONITORADOR IS
	PORT(distancia:IN STD_LOGIC_VECTOR(2 DOWNTO 0);
		 sensor,senha_reg: IN  STD_LOGIC_VECTOR(7 DOWNTO 0);
		 b1,b2,b3,enable,clk:IN STD_LOGIC;
		 led_requer_senha:OUT STD_LOGIC;
		 dig1,dig2:OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
		 cont30seg:BUFFER STD_LOGIC;
		 confirm:OUT STD_LOGIC;
		 b0:BUFFER STD_LOGIC);
END COMPONENT;


COMPONENT FREQ_ALARME IS
	GENERIC(frequencia:INTEGER:=33333333);
	PORT(clk66,enable:IN STD_LOGIC;
		saida:BUFFER STD_LOGIC);
END COMPONENT;
END PACKAGE;